# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b689c49d0e0d9bb234be53489a5b6c67e0e65082c0353f00c6801d68141c9d13f9d0e5ca50960279db6d21d6cb25a863eefd0efd0e8e386198aadf8a981a3c6

test:
  secret_key_base: 1d6ee8cef80757cd3a7798293d7adf729a74452e0a13b75f372000f4eccd1b03cf11b4fe07ff80a3ce87374c62fb8c206ba8ac7748f0e1c273704199323a2cb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
